import React, { useCallback, useState } from 'react';
import { Linking } from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import { api } from '../../lib/api';
import { useSession } from '../../lib/session';
import { Trip, User, dateText } from '../../lib/types';
import { Page, Card, Heading, Body, Badge, Button, Field, Choices, Notice, Loading, useLoad, message, Stats } from '../../components/ui';
export default function TripDetail() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { user } = useSession();
  const { data: trip, error, loading, refresh } = useLoad(useCallback(() => api<Trip>('/trips/' + id), [id]));
  const [drivers, setDrivers] = useState<User[] | null>(null); const [odometer, setOdometer] = useState(''); const [notes, setNotes] = useState(''); const [reason, setReason] = useState(''); const [rating, setRating] = useState('5'); const [comment, setComment] = useState(''); const [actionError, setActionError] = useState(''); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState('');
  async function action(endpoint: string, body: unknown) { setBusy(true); setActionError(''); setNotice(''); try { await api(`/trips/${id}/${endpoint}`, 'POST', body); setDrivers(null); setOdometer(''); setNotice('Trip updated.'); await refresh(); } catch (e) { setActionError(message(e)); } finally { setBusy(false); } }
  async function candidates() { setBusy(true); setActionError(''); try { setDrivers(await api<User[]>(`/trips/${id}/candidates`)); } catch (e) { setActionError(message(e)); } finally { setBusy(false); } }
  async function open(url: string) { try { await Linking.openURL(url); } catch { setActionError('Could not open this link on your device.'); } }
  return <Page back title={trip?.title || 'Journey details'} subtitle="All the details for a well-planned journey." loading={loading} refresh={() => void refresh()}>
    <Notice text={error || actionError} error/><Notice text={notice}/><Loading show={loading && !trip}/>
    {trip && <><Card><Badge status={trip.status}/><Heading>{trip.pickup} → {trip.destination}</Heading><Body>Other stops: {trip.stops || 'None'}</Body><Body>Departure: {dateText(trip.startAt)}{ '\n' }Return: {dateText(trip.endAt)}</Body><Stats values={[[ 'Estimated km',trip.estimatedKm],['Passengers',trip.passengers],['Actual km',trip.actualKm ?? '—']]}/><Body>{trip.vehicleType} · {trip.department?.departmentName || trip.department?.name}</Body><Body>{trip.notes || 'No additional requirements.'}</Body><Button secondary title="Open route in Maps ↗" onPress={() => void open(`https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(trip.pickup)}&destination=${encodeURIComponent(trip.destination)}`)}/></Card>
    <Card><Heading>People & contact</Heading><Body>Contact: {trip.contactName} · {trip.contactPhone}</Body><Button secondary title="Call trip contact" onPress={() => void open('tel:' + trip.contactPhone)}/>{trip.driver ? <><Body>Driver: {trip.driver.name}{'\n'}Vehicle: {trip.driver.vehicleType} · {trip.driver.vehiclePlate}</Body><Button secondary title={`Call ${trip.driver.name}`} onPress={() => void open('tel:' + trip.driver?.phone)}/></> : <Body>HR has not assigned a driver yet.</Body>}</Card>
    {user?.role === 'hr' && trip.status === 'requested' && <Card><Heading>Assign a driver</Heading><Body>Only available drivers with the right vehicle, capacity, valid uploaded licence and no conflicting journey are shown.</Body><Button title="Find available drivers" onPress={() => void candidates()} disabled={busy}/>{drivers?.map(d => <Button secondary key={d._id} title={`${d.name} · ${d.vehiclePlate} · Assign`} disabled={busy} onPress={() => void action('assign',{driverId:d._id})}/>)}{drivers?.length === 0 && <Notice text="No suitable drivers. Check availability, vehicle type, capacity and licence records in People."/>}</Card>}
    {user?.role === 'driver' && ['assigned','in_progress'].includes(trip.status) && <Card><Heading>{trip.status === 'assigned' ? 'Ready to depart?' : 'Complete your journey'}</Heading>{trip.startOdometer !== undefined && <Body>Start odometer: {trip.startOdometer} km</Body>}<Field label={trip.status === 'assigned' ? 'Starting odometer (km)' : 'Ending odometer (km)'} value={odometer} onChangeText={setOdometer} keyboardType="decimal-pad"/>{trip.status === 'in_progress' && <Field label="Completion notes" value={notes} onChangeText={setNotes} multiline/>}<Button disabled={busy || !odometer.trim()} title={trip.status === 'assigned' ? 'Start trip' : 'Complete trip & save distance'} onPress={() => void action(trip.status === 'assigned' ? 'start' : 'complete', { odometer: Number(odometer), notes })}/></Card>}
    {trip.status === 'completed' && <Card><Heading>Journey complete</Heading><Body>Odometer: {trip.startOdometer} → {trip.endOdometer} km{'\n'}Distance travelled: {trip.actualKm} km{'\n'}{trip.completionNotes}</Body>{trip.feedback?.rating ? <><Heading>{trip.feedback.rating} / 5 · Feedback</Heading><Body>{trip.feedback.comment || 'No written feedback.'}</Body></> : user?.role === 'department' ? <><Choices label="Rate your driver" value={rating} onChange={setRating} options={['1','2','3','4','5']}/><Field label="Your feedback" value={comment} onChangeText={setComment} multiline/><Button title="Submit feedback" disabled={busy} onPress={() => void action('feedback',{rating:Number(rating),comment})}/></> : <Body>Waiting for department feedback.</Body>}</Card>}
    {['hr','department'].includes(user?.role || '') && ['requested','assigned'].includes(trip.status) && <Card><Heading>Change of plans?</Heading><Field label="Reason for cancellation / rejection" value={reason} onChangeText={setReason}/><Button secondary title="Cancel this trip" disabled={busy || !reason.trim()} onPress={() => void action('decision',{action:'cancelled',reason})}/>{user?.role === 'hr' && trip.status === 'requested' && <Button secondary title="Reject request" disabled={busy || !reason.trim()} onPress={() => void action('decision',{action:'rejected',reason})}/>}</Card>}
    {!!trip.decisionNote && <Notice text={trip.decisionNote}/>}<Card><Heading>Journey timeline</Heading>{trip.history.map((h,i) => <Body key={i}>{dateText(h.at)} · {h.status.replaceAll('_',' ')}{h.note ? ` — ${h.note}` : ''}</Body>)}</Card></>}
  </Page>;
}
